# Generated by Django 3.1.3 on 2021-04-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegename', models.CharField(max_length=255)),
                ('teamname', models.CharField(max_length=255)),
                ('name1', models.CharField(max_length=50)),
                ('name2', models.CharField(max_length=50)),
                ('name3', models.CharField(max_length=50)),
                ('email1', models.EmailField(max_length=100)),
                ('email2', models.EmailField(max_length=100)),
                ('email3', models.EmailField(max_length=100)),
                ('phnumber1', models.CharField(max_length=50)),
                ('phnumber2', models.CharField(max_length=50)),
                ('phnumber3', models.CharField(max_length=50)),
                ('proof_pic', models.FileField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
